name: 2024-sp-plug-and-abandonment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.22
  - scipy>=1.8
  - pymatsolver>=0.3
  - matplotlib-base
  - discretize>=0.11
  - simpeg
  - geoana>=0.7
  - libdlf
  - pandas
  - choclo>=0.3.0
  - scooby
  - jupyter
  - pydiso
